# Generated by Django 2.1 on 2018-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('university', models.CharField(choices=[('UTS', 'UTS'), ('UNSW', 'UNSW'), ('USYD', 'USYD'), ('UWS', 'UWS'), ('UOW', 'UOW'), ('UON', 'UON'), ('TAFE', 'TAFE'), ('MQU', 'MQU')], default='', max_length=100)),
                ('summary', models.FileField(default='', upload_to='')),
                ('pitch_deck', models.FileField(default='', upload_to='')),
                ('comments', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
