# Generated by Django 2.1 on 2018-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pitch_deck',
        ),
        migrations.AddField(
            model_name='application',
            name='slides',
            field=models.FileField(default='', upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='summary',
            field=models.FileField(default='', upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.CharField(choices=[('UTS', 'University of Technology Sydney'), ('UNSW', 'University of New South Wales'), ('USYD', 'University of Sydney'), ('MQU', 'University of Macquaarie'), ('UOW', 'University of Wollongong'), ('ACU', 'Australian Catholic University'), ('UNE', 'University of New England'), ('SCU', 'Southern Cross University'), ('CSU', 'Charles Sturt University'), ('TAFE', 'TAFE')], default='', max_length=100),
        ),
    ]
